### ISSUE TITLE
Error: `'cp '' /home/runner/work/app/app/apk-release.apk'`

### ISSUE THREAD

**Issue by tachibana-shin** [sparkfabrik/android-build-action#10]
This happens when I use the autosign function of this action.

Report: https://github.com/anime-vsub/app/actions/runs/3255938756/jobs/5345830720

**Comment by edodusi** [comment]
It's kinda strange because `GRADLE_APK_OUTPUT_PATH` seems to be set. Happens everytime?

**Comment by tachibana-shin** [comment]
it will happen if i try to use `action` APK signing function it will work properly if i disable apk signing

**Comment by luke-rogers** [comment]
I ran into this issue when using `build-type: bundle` and `gradle-task: assembleRelease`. Changing to `gradle-task: bundleRelease` causes the abb to be built rather than the apk, fixing the issue.

Some documentation around this would be useful.
