### ISSUE TITLE
Warning: Unexpected input(s)

### ISSUE THREAD

**Issue by darthleonard** [sparkfabrik/android-build-action#11]
My project is on Ionic 6 with capacitor 4, I am trying to generate a signed aab, but I got this message and the .aab file is not signed

`Warning: Unexpected input(s) 'build-type', 'package-name', 'keystore-content', 'keystore-password', 'keystore-alias', valid inputs are ['project-path', 'output-path', 'gradle-task', 'browserstack-upload', 'browserstack-username', 'browserstack-access-key']`

this is the config I am using

>         name: Android Build Bundle
>         uses: sparkfabrik/android-build-action@v1.0.0
>         with:
>           project-path: ./android/
>           build-type: bundle
>           output-path: app-release.aab
>           package-name: com.my.app
>           keystore-content: ${{ secrets.ANDROID_SIGNING_KEY }}
>           keystore-password: ${{ secrets.ANDROID_KEY_PASSWORD }}
>           keystore-alias: ${{ secrets.ANDROID_KEY_ALIAS }}
>           browserstack-upload: false

Am I missing a version or simething?

**Comment by edodusi** [comment]
Hi @darthleonard I think you are using an old version of the Action, this should work with the latest release.
