### ISSUE TITLE
missing plugin

### ISSUE THREAD

**Issue by gustavocnp95** [sparkfabrik/android-build-action#13]
Some days ago the action started to throw an error:

In Gemfile:
  fastlane-plugin-browserstack was resolved to 0.3.2, which depends on
    rest-client was resolved to 2.1.0, which depends on
      netrc
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
/var/lib/gems/3.0.0/gems/bundler-2.4.5/lib/bundler/resolver.rb:293:in `raise_not_found!': Could not find gem 'fastlane-plugin-browserstack' in locally installed gems. (Bundler::GemNotFound)

**Comment by francescoben** [comment]
hi @gustavocnp95, we just released a [new version](https://github.com/sparkfabrik/android-build-action/releases/tag/v1.3.0) that should fix the problem, could you try it?

**Comment by gustavocnp95** [comment]
Thank you for fix it, but actually I replaced the action with a simple gradlew command. Hope it works well! 👊

**Comment by francescoben** [comment]
ok so I'm closing this issue, thanks for the feedback!
